### ISSUE TITLE
expect_the_only(Klass) matcher?

### ISSUE THREAD

**Issue by dfaulken** [umts/custom-matchers#7]
A pretty common design pattern we've fallen into is to write `expect_any_instance_of(Klass)` when because our tests are hermetic, there's exactly one `Klass` in existence.

It'd be nice to make this clear by writing something like `expect_the_only(Klass)` instead, which would also come with an assertion that there's actually only one `Klass`.

**Comment by ennukee** [comment]
```ruby
module RSpec
  module Mocks
    ::RSpec::Mocks::ExampleMethods.class_exec do
      def expect_only_instance_of(klass)
        expect(klass.count).to be(1)
        AnyInstanceExpectationTarget.new(klass)
      end
    end
  end
end
```

**Comment by dfaulken** [comment]
Cool, you're welcome to open a PR (with some specs) 😄

**Comment by werebus** [comment]
We're generally discouraging use of `any_instance_of` at all at this point ([ref](https://relishapp.com/rspec/rspec-mocks/docs/working-with-legacy-code/any-instance)).
